<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Process Entries</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
    admin = {
        execute : function(){
            const self = this;
            $.ajax({
                url: "<?php echo Mage::getUrl('process/adminhtml_process_upload/processEntry/'); ?>",
                type: 'POST',
                data: $("#processForm").serialize(),
                dataType: 'json',
                success: function(data){
                    console.log(data);
                    if(data.message){
                        $("#process").html(data.message);
                    }
                    if(data.status == "success" && data.reload == false){
                        self.execute();
                    }
                    else if(data.status == "success" && data.reload == true){
                        location.reload(true);
                    }
                    else if(data.status == 'failuer'){
                        location.reload();
                    }
                }             
            });
        },
    }
    </script>
</head>
<body>
    <form action="#" method="post" id="processForm">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    </form>
    <h1 id="process">Processing</h1>

<script type="text/javascript">
        admin.execute();
    </script>
</body>
</html>

